spring.datasource.url=jdbc:mysql://localhost:3306/ADMIRE_CARS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=ADS_PRD
spring.datasource.password=ENC(pjyKjQfCcl8V7kyJLwpl8jfg2fprHLtpPmeh2j6Hq2txtYzL1UM8o7gWXZffig3J)
spring.datasource.hikari.pool-name=AdsRunnerHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2A
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=240000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.validation-timeout=5000

## logging configuration
logging.level.com.admire.cars.runner=INFO

## Disable SQL logging in production
spring.jpa.show-sql=false