spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ADMIRE_CARS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ADS_PRD}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ENC(pjyKjQfCcl8V7kyJLwpl8jfg2fprHLtpPmeh2j6Hq2txtYzL1UM8o7gWXZffig3J)}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.hikari.pool-name=AdsRunnerHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=240000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.validation-timeout=5000

## logging configuration
logging.level.com.admire.cars.runner=info

## Disable SQL logging in production
spring.jpa.show-sql=false

# JWT settings
jwt.secret=${JWT_SECRET:ads_runner_secret_key}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:1800}