UPDATE TOOL_OUTCOME
SET OUTCOME_TYPE = CASE
    WHEN OUTCOME_TYPE IS NULL OR TRIM(OUTCOME_TYPE) = '' THEN OUTCOME_TYPE
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) IN ('MEDIABY', 'MEDIA BY') THEN 'MEDIA_BY'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) IN ('IP PROXY', 'STATIC IP') THEN 'STATIC_IP'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) = 'DYNAMIC IP' THEN 'DYNAMIC_IP'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) = 'CLOUD PHONE' THEN 'CLOUD_PHONE'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) = 'VPN' THEN 'VPN'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) = 'VPS' THEN 'VPS'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) IN ('ADSPOWER BROWSER', 'ADS POWER BROWSER', 'ADS POWER BROSWER') THEN 'ADS_POWER_BROWSER'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) = 'SEMRUSH' THEN 'SEMRUSH'
    WHEN UPPER(REPLACE(TRIM(OUTCOME_TYPE), '_', ' ')) = 'OTHERS' THEN 'OTHERS'
    ELSE OUTCOME_TYPE
END
WHERE OUTCOME_TYPE IS NOT NULL
  AND TRIM(OUTCOME_TYPE) <> '';
